## M.Tyka Sep. 06
import string
import sys
import re

if len(sys.argv) <= 1:
  print 'Syntax: python modifypd.py interface.py\n'
  print '     This script will modify an interface file generated by SWIG '
  print '     and modify the behaviour of the exported classes such that an '
  print '     exception is thrown if the user attempts to add or overwrite '
  print '     an attribute to a wrapped class '
  sys.exit(1)


file = open(sys.argv[1],'r')
alllines = string.split(file.read(),'\n')
file.close()

file = open(sys.argv[1],'w')
fileold = open(sys.argv[1] + ".old",'w')

matches = 0

for iline,line in enumerate(alllines):
  fileold.write(line)
  fileold.write('\n')


  ## Change Error message for missing member 
  if( line[0:58] == '        raise AttributeError("You cannot add attributes to' ):
    print 'modifypd.py : Beautifying error message 1 ... ok'
    file.write('        raise AttributeError("Class \'%s\' has no member \'%s\' " %( self.__class__.__name__, str(name)) )')
    continue
  ## Change Error message for missing member 
  if( line[0:42] == '    raise AttributeError,name' ):
    print 'modifypd.py : Beautifying error message 2 ... ok'
    file.write('    raise AttributeError("Class \'%s\' has no member \'%s\' " %( self.__class__.__name__, str(name)) )')
    continue

  file.write(line)
  file.write('\n')


file.close()
fileold.close()

sys.exit(0)

